In [1]:
paragraph = """
Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated. At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time worker for the RSS in Gujarat in 1971. The RSS assigned him to the BJP in 1985 and he held several positions within the party hierarchy until 2001, rising to the rank of general secretary.
"""

In [2]:
paragraph


'\nModi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated. At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time worker for the RSS in Gujarat in 1971. The RSS assigned him to the BJP in 1985 and he held several positions within the party hierarchy until 2001, rising to the rank of general secretary.\n'

In [3]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [4]:
#tokenization - paragraph into sentences - words

nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\anosh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [5]:
sentences = nltk.sent_tokenize(paragraph)

In [6]:
sentences

['\nModi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education.',
 'He was introduced to the RSS at the age of eight.',
 'His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated.',
 'At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so.',
 'Modi became a full-time worker for the RSS in Gujarat in 1971.',
 'The RSS assigned him to the BJP in 1985 and he held several positions within the party hierarchy until 2001, rising to the rank of general secretary.']

In [7]:
len(sentences)

6

In [8]:
stemmer = PorterStemmer()

In [9]:
stemmer.stem('history')

'histori'

In [11]:
from nltk.stem import WordNetLemmatizer

In [12]:
lemmatizer=WordNetLemmatizer()

In [17]:
lemmatizer.lemmatize('goes')

'go'

In [10]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\anosh\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [13]:
lemmatizer.lemmatize('history')

'history'

In [19]:
import re

corpus = []

for i in range(len(sentences)):
    text = re.sub('[^a-zA-Z]', ' ', sentences[i])
    text = text.lower()
    corpus.append(text)

In [20]:
corpus

[' modi was born and raised in vadnagar in northeastern gujarat  where he completed his secondary education ',
 'he was introduced to the rss at the age of eight ',
 'his account of helping his father sell tea at the vadnagar railway station has not been reliably corroborated ',
 'at age     he was married to jashodaben modi  whom he abandoned soon after  only publicly acknowledging her four decades later when legally required to do so ',
 'modi became a full time worker for the rss in gujarat in      ',
 'the rss assigned him to the bjp in      and he held several positions within the party hierarchy until       rising to the rank of general secretary ']

In [24]:
##stemming

for i in corpus:
    words = nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')): #remove stopwords
            print(lemmatizer.lemmatize(word))

modi
born
raised
vadnagar
northeastern
gujarat
completed
secondary
education
introduced
r
age
eight
account
helping
father
sell
tea
vadnagar
railway
station
reliably
corroborated
age
married
jashodaben
modi
abandoned
soon
publicly
acknowledging
four
decade
later
legally
required
modi
became
full
time
worker
r
gujarat
r
assigned
bjp
held
several
position
within
party
hierarchy
rising
rank
general
secretary


In [22]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\anosh\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer() #binary=True to keep only 0s and 1s

In [26]:
X = cv.fit_transform(corpus)

In [28]:
cv.vocabulary_


{'modi': 38,
 'was': 66,
 'born': 11,
 'and': 5,
 'raised': 47,
 'in': 32,
 'vadnagar': 65,
 'northeastern': 39,
 'gujarat': 23,
 'where': 68,
 'he': 25,
 'completed': 12,
 'his': 31,
 'secondary': 53,
 'education': 16,
 'introduced': 33,
 'to': 63,
 'the': 61,
 'rss': 52,
 'at': 7,
 'age': 4,
 'of': 41,
 'eight': 17,
 'account': 1,
 'helping': 27,
 'father': 18,
 'sell': 55,
 'tea': 60,
 'railway': 46,
 'station': 59,
 'has': 24,
 'not': 40,
 'been': 9,
 'reliably': 49,
 'corroborated': 13,
 'married': 37,
 'jashodaben': 34,
 'whom': 69,
 'abandoned': 0,
 'soon': 58,
 'after': 3,
 'only': 42,
 'publicly': 45,
 'acknowledging': 2,
 'her': 28,
 'four': 20,
 'decades': 14,
 'later': 35,
 'when': 67,
 'legally': 36,
 'required': 50,
 'do': 15,
 'so': 57,
 'became': 8,
 'full': 21,
 'time': 62,
 'worker': 71,
 'for': 19,
 'assigned': 6,
 'him': 30,
 'bjp': 10,
 'held': 26,
 'several': 56,
 'positions': 44,
 'within': 70,
 'party': 43,
 'hierarchy': 29,
 'until': 64,
 'rising': 51,
 'rank':

In [29]:
corpus[0]

' modi was born and raised in vadnagar in northeastern gujarat  where he completed his secondary education '

In [30]:
X[0].toarray() #bag of words

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0]], dtype=int64)

In [32]:
X[0].shape

(1, 72)

In [15]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

corpus = []

# Assuming sentences is defined somewhere
for sentence in sentences:
    words = re.sub('[^a-zA-Z]', ' ', sentence)
    words = words.lower()
    words = words.split()
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]
    words = ' '.join(words)
    corpus.append(words)


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\anosh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\anosh\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [16]:
corpus

['modi born raised vadnagar northeastern gujarat completed secondary education',
 'introduced r age eight',
 'account helping father sell tea vadnagar railway station reliably corroborated',
 'age married jashodaben modi abandoned soon publicly acknowledging four decade later legally required',
 'modi became full time worker r gujarat',
 'r assigned bjp held several position within party hierarchy rising rank general secretary']

In [17]:
#BOW
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(binary = True, ngram_range=(2,3))

In [18]:
X = cv.fit_transform(corpus)

In [19]:
cv.vocabulary_

{'modi born': 49,
 'born raised': 15,
 'raised vadnagar': 61,
 'vadnagar northeastern': 81,
 'northeastern gujarat': 51,
 'gujarat completed': 28,
 'completed secondary': 17,
 'secondary education': 68,
 'modi born raised': 50,
 'born raised vadnagar': 16,
 'raised vadnagar northeastern': 62,
 'vadnagar northeastern gujarat': 82,
 'northeastern gujarat completed': 52,
 'gujarat completed secondary': 29,
 'completed secondary education': 18,
 'introduced age': 36,
 'age eight': 6,
 'introduced age eight': 37,
 'account helping': 2,
 'helping father': 32,
 'father sell': 21,
 'sell tea': 69,
 'tea vadnagar': 77,
 'vadnagar railway': 83,
 'railway station': 59,
 'station reliably': 75,
 'reliably corroborated': 65,
 'account helping father': 3,
 'helping father sell': 33,
 'father sell tea': 22,
 'sell tea vadnagar': 70,
 'tea vadnagar railway': 78,
 'vadnagar railway station': 84,
 'railway station reliably': 60,
 'station reliably corroborated': 76,
 'age married': 7,
 'married jashodab

In [20]:
corpus[0]

'modi born raised vadnagar northeastern gujarat completed secondary education'

In [21]:
X[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0]],
      dtype=int64)

In [22]:
X

<6x88 sparse matrix of type '<class 'numpy.int64'>'
	with 88 stored elements in Compressed Sparse Row format>

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv = TfidfVectorizer(ngram_range  = (1,3), max_features = 3)
X = cv.fit_transform(corpus)


In [32]:
corpus[0]

'modi born raised vadnagar northeastern gujarat completed secondary education'

In [33]:
X[0].toarray()

array([[0.60714432, 0.51259296, 0.60714432]])